const problems = [
  { id: '1001', name: '打印沙漏', score: 20, state: 'done' }, { id: '1002', name: '写出这个数', score: 20, state: 'done' }, { id: '1003', name: '个位数统计', score: 20, state: 'active' }, { id: '1004', name: '成绩转换', score: 15, state: '' }, { id: '1005', name: '继续(3n+1)猜想', score: 20, state: '' }
];
let currentIndex = 2;
const code = document.querySelector('#code');
const lineNumbers = document.querySelector('#line-numbers');
const content = '<p>给定一个不超过 <b>1000 位</b>的正整数 <code>N</code>，请统计其中每种个位数字出现的次数。</p><p>输出时按数字从小到大的顺序，每行输出一个数字和一个冒号，再输出该数字在 <code>N</code> 中出现的次数。</p>';
const starterCode = "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    string n;\n    cin >> n;\n    int digitCount[10] = {0};\n\n    for (char ch : n) {\n        digitCount[ch - '0']++;\n    }\n\n    for (int i = 0; i < 10; i++) {\n        if (digitCount[i]) {\n            cout << i << ':' << digitCount[i] << '\\n';\n        }\n    }\n    return 0;\n}";
function renderMatrix(){document.querySelector('#problem-matrix').innerHTML=problems.map((p,i)=>`<button class="problem-cell ${p.state}" data-index="${i}" title="${p.id} ${p.name}">${p.state==='done'?'✓':i+1}</button>`).join('');document.querySelectorAll('.problem-cell').forEach(el=>el.onclick=()=>selectProblem(Number(el.dataset.index)))}
function selectProblem(index){currentIndex=index;problems.forEach((p,i)=>p.state=i<2?'done':i===index?'active':'');const p=problems[index];document.querySelector('#bar-title').textContent=`${p.id} ${p.name}`;document.querySelector('#problem-title').textContent=`${p.id} ${p.name}`;document.querySelector('.score-label').textContent=`分数 ${p.score}`;document.querySelector('#problem-content').innerHTML=index===2?content:`<p>请根据题目要求完成 <b>${p.name}</b>。提交后，AI 助教将对程序逻辑、边界条件和风格给出反馈。</p>`;document.querySelector('#submit-state').textContent='无提交记录';renderMatrix()}
function updateLineNumbers(){lineNumbers.innerHTML=Array.from({length:Math.max(18,code.value.split('\n').length)},(_,i)=>i+1).join('<br>')}
function setFeedback(kind,title,text){const box=document.querySelector('#ai-feedback');box.className=`ai-feedback ${kind}`;box.innerHTML=`<span>${kind==='success'?'✓':kind==='loading'?'◌':'✦'}</span><p><b>${title}</b><br>${text}</p>`}
code.value=starterCode;updateLineNumbers();renderMatrix();selectProblem(currentIndex);code.addEventListener('input',updateLineNumbers);
document.querySelector('#prev-btn').onclick=()=>selectProblem((currentIndex+problems.length-1)%problems.length);document.querySelector('#next-btn').onclick=()=>selectProblem((currentIndex+1)%problems.length);
document.querySelector('#submit-btn').onclick=async()=>{const btn=document.querySelector('#submit-btn');btn.disabled=true;btn.textContent='AI 正在评测…';setFeedback('loading','正在调用 AI 评测','正在分析代码逻辑、边界条件和输出格式…');try{const response=await fetch('/api/ai-evaluate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({problemId:problems[currentIndex].id,language:document.querySelector('#language').value,code:code.value})});if(!response.ok)throw new Error('demo');const result=await response.json();setFeedback(result.status||'success',result.title||'AI 评测完成',result.feedback||'代码已通过评测。')}catch(_){await new Promise(resolve=>setTimeout(resolve,850));const ok=code.value.includes('digitCount')&&code.value.includes('return');setFeedback(ok?'success':'error',ok?'AI 评测通过 · 20 / 20':'AI 发现待改进项',ok?'逻辑正确，已覆盖数字统计和未出现数字的过滤。建议将输入校验封装为独立函数。':'当前代码可能没有完整处理输入、循环或输出格式。请修改后重新提交。');document.querySelector('#submit-state').textContent=ok?'刚刚提交 · AI 评测通过':'刚刚提交 · 待修改'}finally{btn.disabled=false;btn.textContent='提交本题作答'}};
document.querySelectorAll('.rail-item').forEach(btn=>btn.onclick=()=>{const view=btn.dataset.view;document.querySelectorAll('.rail-item').forEach(x=>x.classList.toggle('selected',x===btn));document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.querySelector(`#${view}-view`).classList.add('active')});document.querySelector('#manage-button').onclick=()=>document.querySelector('#manage-dialog').showModal();
let seconds=6156;setInterval(()=>{seconds=Math.max(0,seconds-1);const h=String(Math.floor(seconds/3600)).padStart(2,'0'),m=String(Math.floor(seconds%3600/60)).padStart(2,'0'),s=String(seconds%60).padStart(2,'0');document.querySelector('#countdown').textContent=`${h}:${m}:${s}`},1000);
const handle=document.querySelector('#drag-handle'),splitter=document.querySelector('#resizable');handle.addEventListener('pointerdown',e=>{handle.setPointerCapture(e.pointerId);handle.classList.add('dragging');const move=event=>{const rect=splitter.getBoundingClientRect();const value=Math.min(Math.max(event.clientX-rect.left,285),rect.width-410);splitter.style.setProperty('--left',`${value}px`)};const up=()=>{handle.classList.remove('dragging');window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)});
