const STORAGE = 'oms-pta-admin-config-v1';
const toLocalDateTime = date => new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);
const defaultExam=window.OMS_EXAM_DATA||{examVersion:'fallback-exam',title:'程序设计考试',duration:120,questions:[{id:'1001',name:'示例题目',score:20,tests:3}]};
const defaultStart = defaultExam.startAt?new Date(defaultExam.startAt):new Date(),defaultEnd=defaultExam.endAt?new Date(defaultExam.endAt):new Date(defaultStart.getTime()+(Number(defaultExam.duration)||120)*60*1000);
const fallback={...defaultExam,startAt:defaultExam.startAt||toLocalDateTime(defaultStart),endAt:defaultExam.endAt||toLocalDateTime(defaultEnd),seat:'PC-08',candidateName:'admin',studentId:'102505201',registered:48};
let config,saved={};try{saved=JSON.parse(localStorage.getItem(STORAGE)||'{}');config=saved.examVersion===fallback.examVersion?{...fallback,...saved}:{...fallback,seat:saved.seat||fallback.seat,candidateName:saved.candidateName||fallback.candidateName,studentId:saved.studentId||fallback.studentId,registered:saved.registered||fallback.registered};}catch{config={...fallback};}if(defaultExam.scheduleVersion&&saved.scheduleVersion!==defaultExam.scheduleVersion){config.startAt=fallback.startAt;config.endAt=fallback.endAt;config.duration=defaultExam.duration;config.scheduleVersion=defaultExam.scheduleVersion;localStorage.setItem(STORAGE,JSON.stringify(config));}if(config.candidateName==='陈小雅')config.candidateName=fallback.candidateName;if(config.studentId==='202401050128')config.studentId=fallback.studentId;if(!config.startAt)config.startAt=fallback.startAt;if(!config.endAt)config.endAt=fallback.endAt;if(!Array.isArray(config.questions)||!config.questions.length)config.questions=fallback.questions;const primaryExamVersion=fallback.examVersion;let primaryConfig=config;let current=0,examExpired=false,activeRoute='info';const results={};const submissions=[];const code=document.querySelector('#code');
let SUBMITTED_CODE_STORAGE='',DRAFT_CODE_STORAGE='',submittedCodes={},draftCodes={};function readCodeMap(key){try{return JSON.parse(localStorage.getItem(key)||'{}')||{};}catch{return {};}}function loadCodeStores(examVersion){SUBMITTED_CODE_STORAGE=`oms-pta-submitted-code-${examVersion}`;DRAFT_CODE_STORAGE=`oms-pta-draft-code-${examVersion}`;submittedCodes=readCodeMap(SUBMITTED_CODE_STORAGE);draftCodes=readCodeMap(DRAFT_CODE_STORAGE);}loadCodeStores(config.examVersion);function submittedCodeForQuestion(questionId){return Object.prototype.hasOwnProperty.call(submittedCodes,questionId)?submittedCodes[questionId]:'';}function codeForQuestion(questionId){return Object.prototype.hasOwnProperty.call(draftCodes,questionId)?draftCodes[questionId]:submittedCodeForQuestion(questionId);}let activeQuestionId=config.questions[current].id;let loadedCode=submittedCodeForQuestion(activeQuestionId);code.value=codeForQuestion(activeQuestionId);
const $=s=>document.querySelector(s);const escape=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function lines(){ $('#lines').textContent=Array.from({length:Math.max(18,code.value.split('\n').length)},(_,i)=>i+1).join('\n'); }
function inlineMarkdown(text){return escape(text).replace(/\[([^\]]+)\]\((https?:\/\/[^)\s]+)\)/g,'<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/__([^_]+)__/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>').replace(/_([^_]+)_/g,'<em>$1</em>');}
function markdownToHtml(source){const lines=String(source).replace(/\r\n?/g,'\n').split('\n');let html='',inCode=false,list='',paragraph=[];const closeParagraph=()=>{if(paragraph.length){html+=`<p>${paragraph.join('<br>')}</p>`;paragraph=[];}};const closeList=()=>{if(list){html+=`</${list}>`;list='';}};const cells=line=>line.trim().replace(/^\||\|$/g,'').split('|').map(cell=>cell.trim());const divider=line=>/^\s*\|?\s*:?-{3,}:?\s*(?:\|\s*:?-{3,}:?\s*)+\|?\s*$/.test(line);for(let index=0;index<lines.length;index++){const raw=lines[index],line=raw.trimEnd();if(/^```/.test(line)){closeParagraph();closeList();if(inCode){html+='</code></pre>';inCode=false;}else{html+='<pre><code>';inCode=true;}continue;}if(inCode){html+=escape(raw)+'\n';continue;}if(line.includes('|')&&index+1<lines.length&&divider(lines[index+1])){closeParagraph();closeList();const header=cells(line);html+='<table><thead><tr>'+header.map(cell=>`<th>${inlineMarkdown(cell)}</th>`).join('')+'</tr></thead><tbody>';index+=2;while(index<lines.length&&lines[index].trim()&&lines[index].includes('|')&&!divider(lines[index])){html+='<tr>'+cells(lines[index]).map(cell=>`<td>${inlineMarkdown(cell)}</td>`).join('')+'</tr>';index++;}html+='</tbody></table>';index--;continue;}if(!line.trim()){closeParagraph();closeList();continue;}if(/^([-*_])\1\1+\s*$/.test(line)){closeParagraph();closeList();html+='<hr>';continue;}const heading=line.match(/^(#{1,6})\s+(.+)$/);if(heading){closeParagraph();closeList();const level=Math.min(3,heading[1].length+1);html+=`<h${level}>${inlineMarkdown(heading[2])}</h${level}>`;continue;}const item=line.match(/^[-*+]\s+(.+)$/),ordered=line.match(/^\d+[.)]\s+(.+)$/);if(item||ordered){closeParagraph();const type=item?'ul':'ol';if(list&&list!==type){closeList();}if(!list){html+=`<${type}>`;list=type;}html+=`<li>${inlineMarkdown((item||ordered)[1])}</li>`;continue;}if(/^>\s?/.test(line)){closeParagraph();closeList();html+=`<blockquote><p>${inlineMarkdown(line.replace(/^>\s?/,''))}</p></blockquote>`;continue;}closeList();paragraph.push(inlineMarkdown(line));}closeParagraph();closeList();if(inCode)html+='</code></pre>';return html;}
function sampleBlock(kind,value){const rows=String(value||'').split('\n');return `<div class="sample-block"><div class="sample-toolbar"><span>[ ${kind} ]</span><div><button type="button">复制内容</button><button type="button">格式</button><button type="button">全屏</button></div></div><div class="sample-rows">${rows.map((row,index)=>`<div><span>${index+1}</span><code>${escape(row)||' '}</code></div>`).join('')}</div></div>`;}
function resourceLimits(){return `<section class="problem-limits" aria-label="资源限制"><div><span>代码长度限制</span><b>16 KB</b></div><div><span>时间限制</span><b>250 ms</b></div><div><span>内存限制</span><b>64 MB</b></div><div><span>栈限制</span><b>8192 KB</b></div></section>`;}
function enhanceStatementSamples(text,q){let html=markdownToHtml(text);const replaceSample=(label,kind,value)=>{if(!value)return;const heading=`(<h[2-4]>${label}[：:]?</h[2-4]>)`,block='<pre><code>[\\s\\S]*?</code></pre>';html=html.replace(new RegExp(`${heading}\\s*${block}`),`$1${sampleBlock(kind,value)}`);};replaceSample('样例输入','in',q.sampleInput||markdownSample(text,'样例输入'));replaceSample('样例输出','out',q.sampleOutput||markdownSample(text,'样例输出'));return html;}
function formatStatement(text,q){const limits=resourceLimits();if(!text)return `<div class="rendered-markdown problem-copy"><p>请根据题目要求完成程序。提交后，AI 助教将检查程序逻辑、边界条件和代码风格。</p><h3>输入格式：</h3><p>输入数据由题目给定。</p><h3>输出格式：</h3><p>按题目要求输出计算结果。</p><h3>输入样例：</h3>${sampleBlock('in',q.sampleInput||'100311')}<h3>输出样例：</h3>${sampleBlock('out',q.sampleOutput||'0:2\n1:3\n3:1')}${limits}</div>`;return `<div class="rendered-markdown problem-copy">${enhanceStatementSamples(text,q)}${limits}</div>`;}
function statusGlyph(status,label){if(status==='accepted')return '<svg viewBox="0 0 24 24" aria-label="答案正确"><path d="m5.5 12.5 4.1 4.1L18.5 7.5"/></svg>';if(status==='wrong')return '<svg viewBox="0 0 24 24" aria-label="答案错误"><path d="m8 8 8 8M16 8l-8 8"/></svg>';return label;}
function updateCountdown(){const start=Date.parse(config.startAt),end=Date.parse(config.endAt),now=Date.now(),remain=$('.remain'),archived=config.category==='past',beforeStart=!archived&&now<start,displayEnded=archived||now>=end,judgeable=config.questions[current]?.judgeable!==false;let milliseconds=archived?0:Math.max(0,beforeStart?start-now:end-now);examExpired=!archived&&now>=end;const seconds=Math.floor(milliseconds/1000),hours=String(Math.floor(seconds/3600)).padStart(2,'0'),minutes=String(Math.floor(seconds%3600/60)).padStart(2,'0'),secs=String(seconds%60).padStart(2,'0');$('#countdown-label').textContent=beforeStart?'距开始':displayEnded?'已结束':'剩余';$('#countdown').textContent=`${hours}:${minutes}:${secs}`;remain.classList.toggle('warning',!displayEnded&&milliseconds<=5*60*1000);remain.classList.toggle('expired',displayEnded);$('#submit').disabled=examExpired||!judgeable;$('#run-test').disabled=examExpired||!judgeable;if(!judgeable)$('#submit-state').textContent='题面资料不完整，暂不支持评测';else if(examExpired)$('#submit-state').textContent='考试已结束';}
function editorCode(){return window.omsCodeEditor?.getValue?.()??code.value;}function saveDraftCode(questionId,source){if(!questionId)return false;draftCodes[questionId]=source;try{localStorage.setItem(DRAFT_CODE_STORAGE,JSON.stringify(draftCodes));return true;}catch{return false;}}function persistActiveDraft(){return saveDraftCode(activeQuestionId,editorCode());}function saveSubmittedCode(questionId,source){if(!questionId)return;submittedCodes[questionId]=source;try{localStorage.setItem(SUBMITTED_CODE_STORAGE,JSON.stringify(submittedCodes));}catch{}saveDraftCode(questionId,source);}function hasUnsavedCode(){return editorCode()!==loadedCode;}function loadCode(source){code.value=source;code.dispatchEvent(new Event('input',{bubbles:true}));lines();}function restoreSavedCode(){const source=codeForQuestion(activeQuestionId);loadedCode=submittedCodeForQuestion(activeQuestionId);loadCode(source);}function changeQuestion(index){if(index===current)return;persistActiveDraft();current=index;activeQuestionId=config.questions[current].id;render();restoreSavedCode();}
function activateExam(examVersion,questionIndex=0){
  const archive=window.OMS_EXAM_ARCHIVE||[];
  const exam=examVersion===primaryExamVersion?primaryConfig:archive.find(item=>item.examVersion===examVersion);
  if(!exam)return false;
  const target=Math.max(0,Math.min(Number(questionIndex)||0,exam.questions.length-1));
  if(config.examVersion===exam.examVersion){changeQuestion(target);return current===target;}
  const identity={seat:primaryConfig.seat,candidateName:primaryConfig.candidateName,studentId:primaryConfig.studentId,registered:primaryConfig.registered,startAt:primaryConfig.startAt,endAt:primaryConfig.endAt};
  persistActiveDraft();config={...exam,...identity};current=target;loadCodeStores(config.examVersion);activeQuestionId=config.questions[current].id;for(const key of Object.keys(results))delete results[key];render();restoreSavedCode();updateCountdown();return true;
}
function render(){const q=config.questions[current],sample=q.testCases?.[0]||{input:q.sampleInput||'',expected:q.sampleOutput||''};$('#exam-name').textContent=config.title;$('#seat').textContent=config.seat;$('#candidate').textContent=config.candidateName;$('#student-id').textContent=config.studentId;$('#bar-title').textContent=`${current+1} ${q.name}`;$('#problem-title').textContent=`${current+1} ${q.name}`;$('#score').textContent=`分数 ${q.score}`;$('#problem-text').innerHTML=formatStatement(q.statement,q);$('#sample-input').value=sample.input||'';$('#expected').textContent=sample.expected||'';const complete=Object.keys(results).length;$('#answer-count').textContent=`${complete} / ${config.questions.length}`;$('#question-grid').innerHTML=config.questions.map((item,index)=>`<button class="${results[index]||''} ${index===current?'current':''}" data-i="${index}" title="${index+1} ${item.name}">${statusGlyph(results[index],index+1)}</button>`).join('');document.querySelectorAll('#question-grid button').forEach(button=>button.onclick=()=>changeQuestion(Number(button.dataset.i)));updateCountdown();}
function renderSubmissions(){return submissions.length?submissions.map(item=>{const index=config.questions.findIndex(question=>question.id===item.problemId);const number=index>=0?index+1:item.problemId;return `<div class="row"><span>${escape(number)}</span><span>${escape(item.language)}</span><span>${escape(item.verdict)}</span><span>${escape(item.time)}</span></div>`;}).join(''):'<div class="row"><span>暂无提交记录</span><span>—</span><span>—</span><span>—</span></div>';}
function formatExamTime(value){const date=new Date(value);if(!Number.isFinite(date.getTime()))return '未设置';return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')} ${String(date.getHours()).padStart(2,'0')}:${String(date.getMinutes()).padStart(2,'0')}`;}
function formatDuration(value){return Number(value)>0?`${Number(value)} 分钟`:'未记录';}
function contestStatus(){const now=Date.now(),start=Date.parse(config.startAt),end=Date.parse(config.endAt);if(config.category==='past')return '已结束';if(Number.isFinite(start)&&now<start)return '未开始';if(Number.isFinite(end)&&now>end)return '已结束';return '进行中';}
function lastSubmissionFor(question){return submissions.find(item=>item.problemId===question.id);}
function renderContestQuestionTable(){const rows=config.questions.map((question,index)=>{const last=lastSubmissionFor(question),status=question.judgeable===false?'资料不完整':results[index]==='accepted'?'答案正确':results[index]==='wrong'?'答案错误':'未提交',tone=results[index]||'pending';return `<button type="button" class="contest-question-row" data-question-open="${index}"><span class="${tone}">${status}</span><span>${last?escape(last.time):'—'}</span><strong><i>${index+1}</i>${escape(question.name)}</strong><em>${Number(question.score)||0} 分</em></button>`;}).join('');return `<section class="contest-question-table"><header><h2>题目列表</h2></header><div class="contest-question-columns"><span>状态</span><span>上次递交</span><span>题目</span><span>分值</span></div>${rows}</section>`;}
function scoreForQuestion(question,index){return results[index]==='accepted'?Number(question.score)||0:0;}
function renderExamInfo(){
  const total=config.questions.reduce((sum,question)=>sum+(Number(question.score)||0),0);
  return `<section class="contest-overview"><div class="contest-heading"><span class="contest-status">${contestStatus()}</span><div><h1>${escape(config.title)}</h1><p><span>程序设计</span><span>${formatExamTime(config.startAt)}</span><span>${formatDuration(config.duration)}</span><span>${Number(config.registered)||1} 人</span><span>${escape(config.candidateName)}</span></p></div></div><div class="contest-home-layout"><main class="contest-home-main"><section class="contest-intro"><h2>比赛介绍</h2><p>Have fun.</p></section>${renderContestQuestionTable()}</main><aside class="contest-facts"><h2>比赛信息</h2><dl><div><dt>状态</dt><dd>${contestStatus()}</dd></div><div><dt>规则</dt><dd>OI</dd></div><div><dt>题数</dt><dd>${config.questions.length}</dd></div><div><dt>开始</dt><dd>${formatExamTime(config.startAt)}</dd></div><div><dt>结束</dt><dd>${formatExamTime(config.endAt)}</dd></div><div><dt>限时</dt><dd>${formatDuration(config.duration)}</dd></div><div><dt>人数</dt><dd>${Number(config.registered)||1}</dd></div><div><dt>考生</dt><dd>${escape(config.candidateName)}</dd></div><div><dt>总分</dt><dd>${total} 分</dd></div></dl></aside></div></section>`;
}
function portalExamStatus(exam){const now=Date.now(),start=Date.parse(exam.startAt),end=Date.parse(exam.endAt);if(exam.category==='past'||(Number.isFinite(end)&&now>=end))return '已结束';if(Number.isFinite(start)&&now<start)return '未开始';return '进行中';}
function portalDuration(value){const minutes=Number(value)||0;if(!minutes)return '未记录';if(minutes%60===0)return `${minutes/60} 小时`;return `${minutes} 分钟`;}
function renderPortalHome(){
  const archive=window.OMS_EXAM_ARCHIVE||[],exams=[primaryConfig,...archive].filter((exam,index,list)=>list.findIndex(item=>item.examVersion===exam.examVersion)===index).sort((a,b)=>Date.parse(b.startAt||b.date||0)-Date.parse(a.startAt||a.date||0));
  const contests=exams.slice(0,5).map(exam=>{const status=portalExamStatus(exam);return `<button type="button" class="portal-contest" data-portal-exam="${escape(exam.examVersion)}"><span class="portal-status ${status==='进行中'?'running':status==='未开始'?'pending':'ended'}">${status}</span><span class="portal-contest-copy"><b>${escape(exam.title)}</b><small><span>♙ OI</span><span>▣ ${formatExamTime(exam.startAt||exam.date)}</span><span>◷ ${portalDuration(exam.duration)}</span><span>♧ ${Number(exam.registered)||1}</span></small></span><span class="portal-arrow">›</span></button>`;}).join('');
  const latest=(primaryConfig.questions||[]).slice(0,8).map((question,index)=>`<button type="button" data-portal-question="${index}"><i>—</i><span>${escape(question.id||String(index+1).padStart(4,'0'))}</span><b>${escape(question.name)}</b></button>`).join('');
  const initial=escape(String(config.candidateName||'U').trim().slice(0,1).toUpperCase()||'U');
  return `<div class="portal-shell"><aside class="portal-sidebar"><div class="portal-brand"><span class="portal-seal">福</span><b>福州大学</b><i>⌃</i></div><nav class="portal-nav" aria-label="主页面导航"><button type="button" class="active" data-portal-route="home"><span>⌂</span><b>首页</b></button><button type="button" data-portal-route="exam"><span>▣</span><b>题目</b></button><button type="button" data-portal-route="advice"><span>▤</span><b>训练</b></button><button type="button" data-portal-route="center"><span>♕</span><b>比赛</b></button><button type="button" data-portal-route="info"><span>▧</span><b>作业</b></button><button type="button" data-portal-route="submissions"><span>☷</span><b>评测</b></button></nav><div class="portal-sidebar-bottom"><button type="button" data-portal-theme><span>◐</span><b>主题切换</b></button><div><span class="portal-service-dot"></span><b>服务状态</b></div><button type="button" data-portal-route="info"><span>ⓘ</span><b>关于</b></button><div class="portal-user"><span>${initial}</span><p><b>${escape(config.studentId||config.candidateName)}</b><small>${escape(config.candidateName)}</small></p><i>⌃</i></div></div></aside><main class="portal-main"><header class="portal-topbar"><span>▣</span><b>福州大学</b></header><div class="portal-content"><div class="portal-primary"><section class="portal-welcome"><h1>欢迎来到 FZU Online Judge!</h1><p>请点击左侧的导航栏寻找你需要的功能。</p></section><section class="portal-section"><header><h2>近期比赛</h2><button type="button" data-portal-route="center">查看全部&nbsp; ›</button></header><div class="portal-contest-list">${contests||'<p class="portal-empty">暂无比赛</p>'}</div></section><section class="portal-section portal-practice"><header><h2>近期训练</h2><button type="button" data-portal-route="exam">进入题目&nbsp; ›</button></header><button type="button" data-portal-exam="${escape(primaryConfig.examVersion)}"><span class="portal-status running">练习</span><b>${escape(primaryConfig.title)}</b><small>${primaryConfig.questions.length} 道题</small></button></section></div><aside class="portal-right"><section class="portal-side-card"><h2>最新题目</h2><div class="portal-problem-list">${latest||'<p class="portal-empty">暂无题目</p>'}</div></section><section class="portal-side-card"><h2>推荐</h2><p class="portal-empty">目前没有推荐内容。</p></section></aside></div></main></div>`;
}
function renderScoreboard(){const solved=config.questions.filter((question,index)=>results[index]==='accepted').length,totalScore=config.questions.reduce((sum,question,index)=>sum+scoreForQuestion(question,index),0);const cells=config.questions.map((question,index)=>{const attempts=submissions.filter(item=>item.problemId===question.id).length,accepted=results[index]==='accepted';return `<td class="score-problem ${accepted?'accepted':''}"><b>${accepted?'✓':attempts?`−${attempts}`:'—'}</b><span>${accepted?`${scoreForQuestion(question,index)} 分`:attempts?`${attempts} 次尝试`:'未提交'}</span></td>`;}).join('');const heads=config.questions.map((question,index)=>`<th><b>${index+1}</b><span>${escape(question.name)}</span></th>`).join('');return `<section class="scoreboard-page"><header><h1>成绩表</h1></header><div class="scoreboard-scroll"><table class="scoreboard-table"><thead><tr><th>#</th><th>用户</th><th><b>Solved</b><span>总得分</span></th>${heads}</tr></thead><tbody><tr><td>1</td><td class="score-user"><span>${escape(String(config.candidateName||'U').slice(0,1).toUpperCase())}</span><b>${escape(config.studentId||config.candidateName)}</b><small>${escape(config.candidateName)}</small></td><td class="score-total"><b>${solved}</b><span>${totalScore} 分</span></td>${cells}</tr></tbody></table></div></section>`;}
function examDate(exam){return exam.date||String(exam.title||'').match(/\d{4}-\d{2}-\d{2}/)?.[0]||'日期未记录';}
function renderExamCards(exams){
  if(!exams.length)return '<div class="exam-center-empty"><b>暂无试卷</b><span>该分区暂时没有可查看的试卷。</span></div>';
  return exams.map((exam,index)=>{
    const total=exam.questions.reduce((sum,question)=>sum+(Number(question.score)||0),0);
    const questions=exam.questions.map((question,questionIndex)=>exam.selectable
      ?`<button type="button" class="archive-question-row" data-exam-version="${escape(exam.examVersion)}" data-question-open="${questionIndex}"><span>${questionIndex+1}</span><div><b>${escape(question.name)}</b><small>编程题</small></div><strong>${Number(question.score)||0} 分</strong><em>进入作答 ›</em></button>`
      :`<div class="archive-question-row"><span>${questionIndex+1}</span><div><b>${escape(question.name)}</b><small>编程题</small></div><strong>${Number(question.score)||0} 分</strong></div>`).join('');
    return `<details class="exam-archive-card" ${index===0||exam.current?'open':''}><summary><div class="archive-card-title"><span class="archive-status ${exam.current?'current':''}">${escape(exam.current?'正在作答':exam.status||'可作答')}</span><div><h2>${escape(exam.title)}</h2></div></div><div class="archive-metrics"><span><small>题目</small><b>${exam.questions.length} 题</b></span><span><small>时长</small><b>${formatDuration(exam.duration)}</b></span><span><small>总分</small><b>${total} 分</b></span></div><i>⌄</i></summary><div class="archive-question-list"><header><span>题目清单</span><span>满分</span></header>${questions}</div></details>`;
  }).join('');
}
function renderExamCenter(){
  const currentExam={...primaryConfig,date:examDate(primaryConfig),status:'模拟卷',current:config.examVersion===primaryExamVersion,selectable:true,category:'mock'};
  const archive=(window.OMS_EXAM_ARCHIVE||[]).filter(exam=>exam.examVersion!==config.examVersion);
  const pastExams=(window.OMS_EXAM_ARCHIVE||[]).filter(exam=>exam.category==='past').map(exam=>({...exam,current:config.examVersion===exam.examVersion,selectable:true}));
  const mockExams=[currentExam,...archive.filter(exam=>exam.category==='mock').map(exam=>({...exam,current:config.examVersion===exam.examVersion,selectable:true}))];
  const activeCategory=config.examVersion===primaryExamVersion?'mock':'past';
  return `<div class="exam-center-head"><h1>考试中心</h1></div><div class="exam-center-tabs" role="tablist"><button type="button" class="${activeCategory==='past'?'active':''}" data-exam-center-tab="past" role="tab" aria-selected="${activeCategory==='past'}">历年卷</button><button type="button" class="${activeCategory==='mock'?'active':''}" data-exam-center-tab="mock" role="tab" aria-selected="${activeCategory==='mock'}">模拟卷</button></div><section class="exam-center-panel ${activeCategory==='past'?'active':''}" data-exam-center-panel="past" ${activeCategory==='past'?'':'hidden'}><header><h2>历年卷</h2><span>历年考试试卷</span></header><div class="exam-archive-list">${renderExamCards(pastExams)}</div></section><section class="exam-center-panel ${activeCategory==='mock'?'active':''}" data-exam-center-panel="mock" ${activeCategory==='mock'?'':'hidden'}><header><h2>模拟卷</h2><span>周练与模拟考试</span></header><div class="exam-archive-list">${renderExamCards(mockExams)}</div></section>`;
}
function renderAdviceQuestionRows(questions,emptyText){
  if(!questions.length)return `<div class="study-advice-empty"><b>${escape(emptyText)}</b><span>完成题目评测后，这里会自动更新。</span></div>`;
  return `<div class="study-advice-question-list">${questions.map(({question,index},order)=>`<button type="button" data-question-open="${index}"><span>${order+1}</span><div><b>${escape(question.name)}</b><small>${Number(question.score)||0} 分 · 编程题</small></div><em>进入作答 ›</em></button>`).join('')}</div>`;
}
const fallbackExperiencePosts=[
  {label:'备考策略',title:'先拿稳分，再攻难题',summary:'用稳定得分建立节奏，再把剩余时间留给复杂题。',sections:[
    {key:'idea',title:'核心思路',body:'机试不是按题号顺序完成的比赛。开场先快速浏览全部题目，把题目分成“立即能写”“需要推导”和“暂时没思路”三类，优先完成边界清晰、验证成本低的题目。'},
    {key:'opening',title:'开场十分钟',body:'先确认每道题的输入输出、数据范围和分值，再选择最稳的一题开始。第一题通过后再继续扩大战果，避免在单题上持续消耗时间。',items:['读清数据范围，判断是否需要特殊算法。','手算样例，确认自己理解了题意。','预估编码与调试时间，决定作答顺序。']},
    {key:'order',title:'推荐作答顺序',body:'先完成能独立写出并能快速验证的题，再处理中等难度题，最后集中处理复杂模拟或算法题。卡住超过预设时间就做标记并暂时跳过。'}
  ]},
  {label:'提交检查',title:'提交前做三项检查',summary:'把低级错误挡在提交按钮之前。',sections:[
    {key:'input',title:'检查输入',body:'确认读取顺序、数据类型和多组数据的结束条件。字符串与整行输入混用时，额外检查换行是否被正确处理。'},
    {key:'boundary',title:'检查边界',body:'至少覆盖最小值、最大值、空结果、只有一个元素和全部相同等情况。循环初值、终止条件和数组下标要逐项核对。'},
    {key:'output',title:'检查输出',body:'确认空格、换行、精度与大小写完全符合题目要求。提交前用样例和一个自造极端数据各运行一次。',items:['不要输出调试文字。','检查整数溢出和浮点精度。','确认末尾空格与换行格式。']}
  ]},
  {label:'错题复盘',title:'错题必须重新独立完成',summary:'复盘的目标是重新建立解题过程，而不是记住旧代码。',sections:[
    {key:'reason',title:'先记录错误原因',body:'把问题归类为读题、思路、边界、实现或调试错误，并用一句话写出真正原因。只记录“粗心”无法指导下一次改进。'},
    {key:'rewrite',title:'关闭旧代码再重写',body:'隔一段时间后不看原代码，从题意、样例和数据范围重新推导并独立实现。只有能够重新写出，才说明已经掌握。'},
    {key:'verify',title:'用同类变化验证',body:'在原测试点之外，再改变数据规模、边界位置或输入形式进行验证，确认方法可以迁移到相似题目。',items:['当天定位错误原因。','间隔后完成一次独立重写。','再做一道同类变化题。']}
  ]}
];
function experienceYear(post){
  const matched=String(post.year||post.label||post.title||'').match(/(?:19|20)\d{2}/);
  return matched?Number(matched[0]):0;
}
const experiencePosts=(Array.isArray(window.OMS_EXPERIENCE_POSTS)&&window.OMS_EXPERIENCE_POSTS.length?window.OMS_EXPERIENCE_POSTS:fallbackExperiencePosts)
  .slice()
  .sort((left,right)=>experienceYear(right)-experienceYear(left)||Array.from(String(left.title||'')).length-Array.from(String(right.title||'')).length||String(left.title||'').localeCompare(String(right.title||''),'zh-CN'));
const EXPERIENCE_FONT_STORAGE='oms-pta-experience-font-size';
let experienceFontSize='medium';
try{const storedFontSize=localStorage.getItem(EXPERIENCE_FONT_STORAGE);if(['small','medium','large'].includes(storedFontSize))experienceFontSize=storedFontSize;}catch{}
function renderExperienceReader(){
  const list=experiencePosts.map((post,index)=>`<button type="button" class="${index===0?'active':''}" data-experience-post="${index}" aria-selected="${index===0}"><small>${escape(post.label)}</small><b>${escape(post.title)}</b></button>`).join('');
  const articles=experiencePosts.map((post,index)=>`<article class="experience-article ${index===0?'active':''}" data-experience-article="${index}" ${index===0?'':'hidden'}><header><small>${escape(post.label)}</small><h2>${escape(post.title)}</h2></header>${post.sections.map(section=>`<section id="experience-${index}-${section.key}"><h3>${escape(section.title)}</h3>${section.markdown?`<div class="experience-markdown">${markdownToHtml(section.markdown)}</div>`:`<p>${escape(section.body)}</p>${section.items?`<ul>${section.items.map(item=>`<li>${escape(item)}</li>`).join('')}</ul>`:''}`}</section>`).join('')}</article>`).join('');
  const outlines=experiencePosts.map((post,index)=>`<nav class="${index===0?'active':''}" data-experience-outline="${index}" ${index===0?'':'hidden'}>${post.sections.map(section=>`<a href="#experience-${index}-${section.key}">${escape(section.title)}</a>`).join('')}</nav>`).join('');
  return `<div class="experience-reader" data-experience-font-size="${experienceFontSize}"><aside class="experience-library"><h3>经验文章</h3>${list}</aside><main class="experience-main">${articles}</main><aside class="experience-outline"><h3>目录</h3>${outlines}</aside></div>`;
}
function renderStudyAdvice(){
  const wrongQuestions=config.questions.map((question,index)=>({question,index})).filter(item=>results[item.index]==='wrong');
  const keyQuestions=config.questions.map((question,index)=>({question,index})).filter(item=>item.question.judgeable!==false).slice(0,6);
  const fontOptions=[['small','小'],['medium','中'],['large','大']].map(([value,label])=>`<button type="button" class="${experienceFontSize===value?'active':''}" data-experience-font="${value}" aria-pressed="${experienceFontSize===value}">${label}</button>`).join('');
  return `<div class="study-advice-head"><h1>备考建议</h1></div><div class="study-advice-tabs" role="tablist"><button type="button" class="active" data-study-tab="experience" role="tab" aria-selected="true">经验贴</button><button type="button" data-study-tab="mistakes" role="tab" aria-selected="false">错题集</button><button type="button" data-study-tab="key" role="tab" aria-selected="false">关键题目</button><button type="button" data-study-tab="knowledge" role="tab" aria-selected="false">知识讲解</button></div><section class="study-advice-panel active" data-study-panel="experience"><header><h2>经验贴</h2><div class="experience-header-tools"><div class="experience-font-controls" role="group" aria-label="经验贴字号"><span>字号</span>${fontOptions}</div></div></header>${renderExperienceReader()}</section><section class="study-advice-panel" data-study-panel="mistakes" hidden><header><h2>错题集</h2></header>${renderAdviceQuestionRows(wrongQuestions,'暂无错题记录')}</section><section class="study-advice-panel" data-study-panel="key" hidden><header><h2>关键题目</h2></header>${renderAdviceQuestionRows(keyQuestions,'暂无可复习题目')}</section><section class="study-advice-panel" data-study-panel="knowledge" hidden><header><h2>知识讲解</h2></header><div class="study-advice-grid knowledge"><article><i>IO</i><div><h3>输入输出与格式</h3><p>掌握多组数据读取、行输入、精度控制以及末尾空格和换行处理。</p></div></article><article><i>01</i><div><h3>循环与边界</h3><p>重点检查初值、终止条件、数组下标和空数据等容易出错的位置。</p></div></article><article><i>AZ</i><div><h3>数组与字符串</h3><p>熟悉遍历、计数、切分、字符判断和常用容器的使用方式。</p></div></article><article><i>↕</i><div><h3>排序与查找</h3><p>理解自定义排序规则、二分边界以及去重和频次统计。</p></div></article></div></section>`;
}
const boundaryBounceAnimations=new WeakMap();
function boundaryBounce(event){
  if(Math.abs(event.deltaY)<2||window.matchMedia?.('(prefers-reduced-motion: reduce)').matches)return;
  const selector='.secondary,.statement-inner,.test-content,.compiler-output,.cm-scroller,.editor textarea';
  let scroller=event.target.closest?.(selector);
  if(!scroller){const secondary=$('#secondary');scroller=!secondary.hidden?secondary:$('.statement-inner');}
  if(!scroller)return;
  const atTop=scroller.scrollTop<=1&&event.deltaY<0;
  const atBottom=scroller.scrollTop+scroller.clientHeight>=scroller.scrollHeight-1&&event.deltaY>0;
  if(!atTop&&!atBottom)return;
  if(typeof scroller.animate!=='function')return;
  boundaryBounceAnimations.get(scroller)?.cancel();
  const distance=Math.min(12,6+Math.abs(event.deltaY)*.025)*(atTop?1:-1);
  const animation=scroller.animate([{transform:'translateY(0)'},{transform:`translateY(${distance}px)`,offset:.34},{transform:'translateY(0)'}],{duration:280,easing:'cubic-bezier(.2,.78,.2,1)'});
  boundaryBounceAnimations.set(scroller,animation);
}
function route(name){
  const previousRoute=activeRoute;activeRoute=name;
  if(previousRoute==='exam'&&name!=='exam')persistActiveDraft();
  const app=$('#pta-app'),isHome=name==='home';app.classList.toggle('portal-mode',isHome);
  document.querySelectorAll('.rail-button').forEach(button=>button.classList.toggle('active',button.dataset.route===name));
  $('.remain').hidden=name==='center'||name==='advice'||isHome;
  const secondary=$('#secondary'),workspace=$('#workspace'),overview=$('#overview');
  if(name==='exam'){if(previousRoute!=='exam')restoreSavedCode();secondary.hidden=true;workspace.hidden=false;overview.hidden=false;return;}
  workspace.hidden=true;overview.hidden=true;secondary.hidden=false;secondary.dataset.page=name;
  if(isHome){
    secondary.innerHTML=renderPortalHome();
    secondary.querySelectorAll('[data-portal-route]').forEach(button=>button.onclick=()=>route(button.dataset.portalRoute));
    secondary.querySelectorAll('[data-portal-exam]').forEach(button=>button.onclick=()=>{if(activateExam(button.dataset.portalExam,0))route('info');});
    secondary.querySelectorAll('[data-portal-question]').forEach(button=>button.onclick=()=>{if(activateExam(primaryExamVersion,Number(button.dataset.portalQuestion)))route('exam');});
    const themeButton=secondary.querySelector('[data-portal-theme]');if(themeButton)themeButton.onclick=()=>{const light=app.classList.toggle('light-mode');try{localStorage.setItem('oms-pta-theme',light?'light':'dark');}catch{}};
    return;
  }
  if(name==='submissions')secondary.innerHTML=`<h1>提交列表</h1><div class="card"><div class="row head"><span>题目</span><span>语言</span><span>状态</span><span>提交时间</span></div>${renderSubmissions()}</div>`;
  if(name==='info'){
    secondary.innerHTML=renderExamInfo();
    secondary.querySelectorAll('[data-question-open]').forEach(button=>button.onclick=()=>{const target=Number(button.dataset.questionOpen);if(activateExam(button.dataset.examVersion||config.examVersion,target))route('exam');});
  }
  if(name==='realtime')secondary.innerHTML=renderScoreboard();
  if(name==='center'){
    secondary.innerHTML=renderExamCenter();
    const showCategory=category=>{
      secondary.querySelectorAll('[data-exam-center-tab]').forEach(button=>{const active=button.dataset.examCenterTab===category;button.classList.toggle('active',active);button.setAttribute('aria-selected',String(active));});
      secondary.querySelectorAll('[data-exam-center-panel]').forEach(panel=>{const active=panel.dataset.examCenterPanel===category;panel.hidden=!active;panel.classList.toggle('active',active);});
    };
    secondary.querySelectorAll('[data-exam-center-tab]').forEach(button=>button.onclick=()=>showCategory(button.dataset.examCenterTab));
    secondary.querySelectorAll('[data-question-open]').forEach(button=>button.onclick=()=>{const target=Number(button.dataset.questionOpen);if(activateExam(button.dataset.examVersion||config.examVersion,target))route('exam');});
  }
  if(name==='advice'){
    secondary.innerHTML=renderStudyAdvice();
    const showAdvicePanel=category=>{
      secondary.querySelectorAll('[data-study-tab]').forEach(button=>{const active=button.dataset.studyTab===category;button.classList.toggle('active',active);button.setAttribute('aria-selected',String(active));});
      secondary.querySelectorAll('[data-study-panel]').forEach(panel=>{const active=panel.dataset.studyPanel===category;panel.hidden=!active;panel.classList.toggle('active',active);});
    };
    secondary.querySelectorAll('[data-study-tab]').forEach(button=>button.onclick=()=>showAdvicePanel(button.dataset.studyTab));
    const setExperienceFontSize=size=>{
      if(!['small','medium','large'].includes(size))return;
      experienceFontSize=size;
      secondary.querySelector('.experience-reader')?.setAttribute('data-experience-font-size',size);
      secondary.querySelectorAll('[data-experience-font]').forEach(button=>{const active=button.dataset.experienceFont===size;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active));});
      try{localStorage.setItem(EXPERIENCE_FONT_STORAGE,size);}catch{}
    };
    secondary.querySelectorAll('[data-experience-font]').forEach(button=>button.onclick=()=>setExperienceFontSize(button.dataset.experienceFont));
    const showExperiencePost=post=>{
      secondary.querySelectorAll('[data-experience-post]').forEach(button=>{const active=button.dataset.experiencePost===post;button.classList.toggle('active',active);button.setAttribute('aria-selected',String(active));});
      secondary.querySelectorAll('[data-experience-article]').forEach(article=>{const active=article.dataset.experienceArticle===post;article.hidden=!active;article.classList.toggle('active',active);});
      secondary.querySelectorAll('[data-experience-outline]').forEach(outline=>{const active=outline.dataset.experienceOutline===post;outline.hidden=!active;outline.classList.toggle('active',active);});
    };
    secondary.querySelectorAll('[data-experience-post]').forEach(button=>button.onclick=()=>showExperiencePost(button.dataset.experiencePost));
    secondary.querySelectorAll('[data-question-open]').forEach(button=>button.onclick=()=>{const target=Number(button.dataset.questionOpen);if(activateExam(config.examVersion,target))route('exam');});
  }
}
document.addEventListener('wheel',boundaryBounce,{passive:true});
function syncTesterToggle(){const tester=$('#tester'),collapsed=tester.classList.contains('collapsed'),toggle=$('#tester-toggle');toggle.setAttribute('aria-label',collapsed?'展开测试用例':'收起测试用例');toggle.title=toggle.getAttribute('aria-label');}
function setTab(tab){const tester=$('#tester');tester.classList.toggle('compiler',tab==='compiler');tester.classList.remove('collapsed');document.querySelectorAll('[data-tab]').forEach(button=>button.classList.toggle('active',button.dataset.tab===tab));syncTesterToggle();}
async function judge(mode){const state=$('#run-state'),q=config.questions[current],questionIndex=current,source=editorCode();if(q.judgeable===false){state.textContent='暂不可评测';$('#compiler-output').textContent='该题原始资料不完整，未提供可靠的输入、输出和测试点。';setTab('compiler');return;}state.textContent='正在运行…';$('#tester').classList.remove('collapsed');$('#tester').classList.add('expanded');syncTesterToggle();try{if(!['127.0.0.1','localhost'].includes(location.hostname))throw Error('在线演示不运行 Dev-C++；请通过本机评测服务运行。');const response=await fetch('/api/judge',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:source,language:$('#language').value,problemId:q.id,input:$('#sample-input').value,mode})});if(!response.ok)throw Error('本机评测服务不可用');const result=await response.json();$('#compiler-output').textContent=result.compilerOutput||result.message||'评测完成。';setTab('compiler');state.textContent=result.verdict==='Accepted'?'答案正确':'答案错误';if(mode==='submit'){results[questionIndex]=result.verdict==='Accepted'?'accepted':'wrong';submissions.unshift({problemId:q.id,language:$('#language').value,verdict:state.textContent,candidate:config.candidateName,time:'刚刚'});saveSubmittedCode(q.id,source);if(activeQuestionId===q.id)loadedCode=source;$('#submit-state').textContent='刚刚提交 · '+state.textContent;render();}}catch(error){$('#compiler-output').textContent=error.message;setTab('compiler');state.textContent='运行失败';}}
function renderSettings(){const area=$('#question-settings');area.innerHTML=config.questions.map((q,i)=>`<div class="question-setting"><span>${escape(q.id)}</span><input data-i="${i}" data-k="name" value="${escape(q.name)}"><input data-i="${i}" data-k="score" type="number" value="${q.score}"><input data-i="${i}" data-k="tests" type="number" value="${q.tests}"></div>`).join('');}
function markdownTestCases(statement){const source=String(statement).replace(/\r\n?/g,'\n');const markers=[...source.matchAll(/^\s*(?:#{1,6}\s*)?(?:测试点|测试用例|test\s*case)\s*(\d+)?(?:\s*[（(][^）)\n]*[）)])?\s*[：:]?\s*$/gmi)];const getValue=(block,names)=>{const label=names.join('|');const fenced=new RegExp('(?:^|\\n)\\s*(?:#{1,6}\\s*)?(?:'+label+')\\s*[：:]?\\s*\\n\\s*```[^\\n]*\\n([\\s\\S]*?)\\n\\s*```','i').exec(block);if(fenced)return fenced[1];const inline=new RegExp('(?:^|\\n)\\s*(?:'+label+')\\s*[：:]\\s*([^\\n]+)','i').exec(block);return inline?inline[1].trim():'';};return markers.map((marker,index)=>{const end=markers[index+1]?markers[index+1].index:source.length;const block=source.slice(marker.index+marker[0].length,end);const input=getValue(block,['标准输入','输入','input']);const expected=getValue(block,['预期输出','输出','output','expected']);return input||expected?{input,expected}:null;}).filter(Boolean);}
function markdownTestCount(statement,cases){const matched=[...String(statement).matchAll(/(?:测试点(?:数|数量|个数)?|(?:测试点|测试用例)\s*总数)\s*[：:]?\s*(\d+)|(\d+)\s*(?:个)?测试点/g)];const declared=matched.reduce((max,item)=>Math.max(max,Number(item[1]||item[2])||0),0);return Math.max(1,declared,cases.length);}
function markdownSample(statement,label){const match=new RegExp('(?:^|\\n)\\s*#{1,6}\\s*'+label+'\\s*\\n\\s*```[^\\n]*\\n([\\s\\S]*?)\\n\\s*```','i').exec(statement);return match?match[1]:'';}
function parseMd(text){const score=Number((text.match(/每题\s*(\d+)\s*分/)||[])[1])||20;const found=[...text.matchAll(/^#{1,4}\s*(\d+)\s*[\.、．\s]+(.+?)\s*$/gm)];if(!found.length)throw Error('未发现“# 1001 题目名称”格式的标题');return found.map((m,i)=>{const begin=m.index+m[0].length,end=found[i+1]?found[i+1].index:text.length,rawStatement=text.slice(begin,end).trim(),testCases=markdownTestCases(rawStatement),statement=rawStatement.split(/^##\s+测试点\s*$/m)[0].replace(/^分数\s+\d+\s*$/m,'').trim();return{id:m[1],name:m[2].trim(),score:Number((rawStatement.match(/(?:分值|分数)\s*[：:]?\s*(\d+)\s*分?/)||[])[1])||score,tests:markdownTestCount(rawStatement,testCases),sampleInput:markdownSample(statement,'样例输入'),sampleOutput:markdownSample(statement,'样例输出'),testCases,statement};});}
$('#overview-toggle').onclick=()=>{$('#pta-app').classList.toggle('overview-collapsed');const closed=$('#pta-app').classList.contains('overview-collapsed');$('#overview-toggle').textContent=closed?'▯':'▮';};$('#previous').onclick=()=>changeQuestion((current+config.questions.length-1)%config.questions.length);$('#next').onclick=()=>changeQuestion((current+1)%config.questions.length);function updateDraftState(){const saved=persistActiveDraft();$('#submit-state').textContent=saved?(hasUnsavedCode()?'草稿已自动保存':'当前代码与最近一次提交一致'):'草稿保存失败，请复制代码后重试';}window.addEventListener('oms-code-save-draft',updateDraftState);window.addEventListener('beforeunload',persistActiveDraft);document.querySelectorAll('.rail-button').forEach(button=>button.onclick=()=>route(button.dataset.route));$('#home-button').onclick=()=>route('home');code.oninput=()=>{lines();updateDraftState();};lines();document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>setTab(button.dataset.tab));$('#tester-toggle').onclick=()=>{const tester=$('#tester');tester.classList.toggle('collapsed');tester.classList.remove('expanded');syncTesterToggle();};syncTesterToggle();$('#reset-test').onclick=()=>{const q=config.questions[current],sample=q.testCases?.[0]||{input:q.sampleInput||'',expected:q.sampleOutput||''};$('#sample-input').value=sample.input||'';$('#expected').textContent=sample.expected||'';$('#run-state').textContent='等待运行';};$('#run-test').onclick=()=>judge('sample');$('#submit').onclick=()=>judge('submit');
const dialog=$('#admin-dialog'),form=$('#admin-form');$('#open-admin').onclick=()=>{for(const [key,value] of Object.entries(config))if(form.elements[key])form.elements[key].value=value;renderSettings();dialog.showModal();};dialog.querySelector('.close').onclick=()=>dialog.close();dialog.querySelector('.cancel').onclick=()=>dialog.close();$('#import-file').onchange=async event=>{const file=event.target.files[0];if(!file)return;try{const text=await file.text();if(/\.md$/i.test(file.name))config.questions=parseMd(text);else if(/\.json$/i.test(file.name)){const data=JSON.parse(text);config.questions=Array.isArray(data)?data:data.questions;}else throw Error('CSV 请使用 JSON 或 Markdown 导入');renderSettings();const tests=config.questions.reduce((total,q)=>total+(Number(q.tests)||0),0),configured=config.questions.reduce((total,q)=>total+(q.testCases||[]).length,0);$('#import-note').textContent=`已识别 ${config.questions.length} 道题、${tests} 个测试点；其中 ${configured} 个已导入输入与预期输出。`;}catch(error){$('#import-note').textContent='导入失败：'+error.message;}event.target.value='';};form.onsubmit=event=>{event.preventDefault();const data=new FormData(form);for(const key of ['title','duration','startAt','endAt','seat','candidateName','studentId','registered'])config[key]=key==='duration'||key==='registered'?Number(data.get(key)):data.get(key);const start=Date.parse(config.startAt),end=Date.parse(config.endAt);if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start){$('#import-note').textContent='结束时间必须晚于开始时间。';return;}config.duration=Math.round((end-start)/60000);document.querySelectorAll('.question-setting').forEach(row=>{const q=config.questions[Number(row.querySelector('[data-k="name"]').dataset.i)];q.name=row.querySelector('[data-k="name"]').value;q.score=Number(row.querySelector('[data-k="score"]').value)||1;q.tests=Number(row.querySelector('[data-k="tests"]').value)||1;});localStorage.setItem(STORAGE,JSON.stringify(config));current=Math.min(current,config.questions.length-1);dialog.close();render();updateCountdown();};render();route('info');updateCountdown();window.setInterval(updateCountdown,1000);
